### ISSUE TITLE
Release v1.4.0

### ISSUE THREAD

**Issue by iCheh** [ev3dev/lmsasm#9]
Hello. I apologize for my bad English, this is the fault of Google translator :).
Compiler v1.4.0 does not work on Windows (my OS is Windows 10 x64), there is no extension, and the compiler does not start (file lmsasm not found).
I made my own build from source code and it works fine.
P.S. I tried to compile v1.4.0 programs with the "--ev3g" flag and without this flag, it seems the byte code does not change, it remains exactly the same.
Thanks for your work.

**Comment by dlech** [comment]
Thanks for pointing this out. I just made a new release that has the proper windows version.

The `--ev3g` flag does 3 things.
- it changes how the floating point number 0.0F is encoded
- it reduces the file size when there are two identical objects
- it changes how labels are encoded in JR instructions

If your program doesn't do any of these, you won't notice any difference.
